import type { NextPage } from 'next'
import { useContext } from 'react';
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import { useMount, useMetaMask, ProviderContext } from "ethers-react";
const Home: NextPage = () => {
    const { test } = useContext(ProviderContext);
    console.log(test)
    const { isConnected, isInstalledWallet } = useMetaMask();
    useMount(() => {
        console.log('loading end....')
        console.log('isConnected....', isConnected)
        console.log('isInstalledWallet....', isInstalledWallet)
    })
    return (
        <div className={styles.container}>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <button onClick={() => {
        
            }}>copy</button>

        </div>
    )
}

export default Home
